// AARIKA role and permission foundation

export const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  DIRECTOR: "DIRECTOR",
  PRINCIPAL: "PRINCIPAL",
  SCHOOL_ADMIN: "SCHOOL_ADMIN",
  TEACHER: "TEACHER",
  STAFF: "STAFF",
  VIEWER: "VIEWER"
});

export const PERMISSIONS = Object.freeze({
  PLATFORM_ADMIN: "platform.admin",
  SCHOOL_VIEW: "school.view",
  SCHOOL_MANAGE: "school.manage",
  USERS_VIEW: "users.view",
  USERS_MANAGE: "users.manage",
  ACADEMICS_VIEW: "academics.view",
  ACADEMICS_MANAGE: "academics.manage",
  ATTENDANCE_VIEW: "attendance.view",
  ATTENDANCE_MANAGE: "attendance.manage",
  DUTIES_VIEW: "duties.view",
  DUTIES_MANAGE: "duties.manage",
  TRANSPORT_VIEW: "transport.view",
  TRANSPORT_MANAGE: "transport.manage",
  MAINTENANCE_VIEW: "maintenance.view",
  MAINTENANCE_MANAGE: "maintenance.manage",
  REPORTS_VIEW: "reports.view",
  AUDIT_VIEW: "audit.view"
});

const ALL = Object.values(PERMISSIONS);

export const ROLE_PERMISSIONS = Object.freeze({
  [ROLES.SUPER_ADMIN]: ALL,
  [ROLES.DIRECTOR]: ALL.filter(p => p !== PERMISSIONS.PLATFORM_ADMIN),
  [ROLES.PRINCIPAL]: [
    PERMISSIONS.SCHOOL_VIEW, PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ACADEMICS_VIEW, PERMISSIONS.ACADEMICS_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.DUTIES_VIEW, PERMISSIONS.DUTIES_MANAGE,
    PERMISSIONS.TRANSPORT_VIEW, PERMISSIONS.TRANSPORT_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.AUDIT_VIEW
  ],
  [ROLES.SCHOOL_ADMIN]: [
    PERMISSIONS.SCHOOL_VIEW, PERMISSIONS.USERS_VIEW, PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.DUTIES_VIEW, PERMISSIONS.DUTIES_MANAGE,
    PERMISSIONS.TRANSPORT_VIEW, PERMISSIONS.TRANSPORT_MANAGE,
    PERMISSIONS.MAINTENANCE_VIEW, PERMISSIONS.MAINTENANCE_MANAGE,
    PERMISSIONS.REPORTS_VIEW
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.SCHOOL_VIEW, PERMISSIONS.ACADEMICS_VIEW, PERMISSIONS.ACADEMICS_MANAGE,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.DUTIES_VIEW, PERMISSIONS.REPORTS_VIEW
  ],
  [ROLES.STAFF]: [
    PERMISSIONS.SCHOOL_VIEW, PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.DUTIES_VIEW, PERMISSIONS.DUTIES_MANAGE,
    PERMISSIONS.TRANSPORT_VIEW, PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.MAINTENANCE_MANAGE
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.SCHOOL_VIEW, PERMISSIONS.ACADEMICS_VIEW,
    PERMISSIONS.ATTENDANCE_VIEW, PERMISSIONS.DUTIES_VIEW,
    PERMISSIONS.TRANSPORT_VIEW, PERMISSIONS.MAINTENANCE_VIEW,
    PERMISSIONS.REPORTS_VIEW
  ]
});

export function hasPermission(role, permission) {
  return Boolean(ROLE_PERMISSIONS[role]?.includes(permission));
}

export function getPermissions(role) {
  return [...(ROLE_PERMISSIONS[role] || [])];
}
