let BANKS=window.AARIKA_QUESTION_BANKS||{},C=null,S=null,subject="";
const $=id=>document.getElementById(id);const KEY="aarikaAdventureLocalV4";
const MATH=[["1","Real Numbers","💎","Number Mine"],["2","Polynomials","🧩","Polynomial Puzzle"],["3","Pair of Linear Equations in Two Variables","🚂","Equation Express"],["4","Quadratic Equations","🏎️","Formula Race"],["5","Arithmetic Progressions","🛤️","Sequence Runner"],["6","Triangles","🏰","Triangle Builder"],["7","Coordinate Geometry","🗺️","Coordinate Explorer"],["8","Introduction to Trigonometry","🎯","Target Quest"],["9","Some Applications of Trigonometry","🚁","Height Hunter"],["10","Circles","🎡","Circle Defender"],["11","Areas Related to Circles","🪙","Circle Treasure"],["12","Surface Areas and Volumes","🧱","Solid Builder"],["13","Statistics","🕵️","Data Detective"],["14","Probability","🎲","Probability Quest"]];
const SCIENCE=[["1","Chemical Reactions and Equations","🧪","Reaction Lab"],["2","Acids, Bases and Salts","⚗️","pH Quest"],["3","Metals and Non-metals","⛏️","Metal Forge"],["4","Carbon and its Compounds","🧬","Carbon City"],["5","Life Processes","🫀","Life Mission"],["6","Control and Coordination","🧠","Neuro Mission"],["7","How do Organisms Reproduce?","🧬","Life Cycle Quest"],["8","Heredity","🧬","Gene Lab"],["9","Light – Reflection and Refraction","🔦","Photon Quest"],["10","The Human Eye and the Colourful World","👁️","Vision World"],["11","Electricity","⚡","Power Grid"],["12","Magnetic Effects of Electric Current","🧲","Magnet Mission"],["13","Our Environment","🌍","Eco Defender"]];
function show(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active")}
function loadBanks(){BANKS=window.AARIKA_QUESTION_BANKS||{}; if(!Object.keys(BANKS).length) alert("Question bank could not be loaded. Please keep questions.js in the same folder.")}
function loadProfile(){let p=JSON.parse(localStorage.getItem(KEY)||"{}");$("score").textContent=p.score||0;$("coins").textContent=p.coins||0;$("rank").textContent=p.rank||"-"}
function chooseSubject(type){subject=type;localStorage.setItem("aarikaName",$("playerName").value.trim()||"Explorer");renderChapters();show("chapters")}
function pdfFor(c){return `https://ncert.nic.in/textbook/pdf/${subject==="science"?"jesc":"jemh"}${String(c[0]).padStart(2,"0")}.pdf`}
function renderChapters(){let arr=subject==="science"?SCIENCE:MATH;$("subjectEyebrow").textContent="CLASS X • "+(subject==="science"?"SCIENCE":"MATHEMATICS");$("chapterGrid").innerHTML=arr.map((c,i)=>`<article class="chapter"><div class="icon">${c[2]}</div><h3>Chapter ${c[0]}: ${c[1]}</h3><div class="game">🎮 ${c[3]}</div><div class="actions"><button class="btn primary" onclick="selectChapter(${i})">VIEW GAME</button><a class="btn pdf" href="${pdfFor(c)}" target="_blank" rel="noopener">📖 NCERT PDF</a></div></article>`).join("")}
function selectChapter(i){let arr=subject==="science"?SCIENCE:MATH;C=arr[i];$("launchIcon").textContent=C[2];$("launchNo").textContent="CLASS X • "+subject.toUpperCase()+" • CHAPTER "+C[0];$("launchTitle").textContent=C[1];$("launchGame").textContent="🎮 "+C[3];$("launchText").textContent="100 CBSE-level questions • surprise events • concept repair • optional NCERT reference";$("chapterPdf").href=pdfFor(C);show("launch")}
function startGame(){let bank=BANKS[subject+"-"+C[0]]||[];S={name:localStorage.getItem("aarikaName")||"Explorer",score:0,coins:0,lives:3,streak:0,correct:0,i:0,t:60,tid:null,qs:[...bank].sort(()=>Math.random()-.5).slice(0,20)};$("gameChapter").textContent="CHAPTER "+C[0]+" • "+C[1];$("gameTitle").textContent=C[3];show("game");loadQ()}
function clock(){clearInterval(S.tid);S.t=60;$("timer").textContent=S.t;S.tid=setInterval(()=>{S.t--;$("timer").textContent=S.t;if(S.t<=0){clearInterval(S.tid);wrong(true)}},1000)}
function loadQ(){let q=S.qs[S.i];$("gameTag").textContent=q.subtopic;$("question").textContent=q.q;$("qNo").textContent=S.i+1;let box=$("targets");box.innerHTML="";q.options.forEach((o,i)=>{let b=document.createElement("button");b.className="target";b.textContent=String.fromCharCode(65+i)+"  "+o;b.onclick=()=>answer(i,b);box.appendChild(b)});hud();clock()}
function hud(){$("gScore").textContent=S.score;$("gCoins").textContent=S.coins;$("gLives").textContent=S.lives;$("gStreak").textContent=S.streak}
function answer(i,b){clearInterval(S.tid);let q=S.qs[S.i];if(i===q.answer){b.classList.add("correct");S.correct++;S.streak++;S.score+=100+(S.streak>=3?25:0);S.coins+=10;$("gameFeedback").textContent=S.streak%3===0?"🎉 SURPRISE! COMBO BONUS!":"💥 TARGET HIT!";setTimeout(next,650)}else wrong(false,b)}
function wrong(timeout,b){let q=S.qs[S.i];S.lives--;S.streak=0;if(b)b.classList.add("wrong");[...$("targets").children].forEach(x=>x.disabled=true);if($("targets").children[q.answer])$("targets").children[q.answer].classList.add("correct");$("mistake").textContent=timeout?"⏰ Time ran out!":"💥 Target missed!";$("reference").innerHTML=`📚 <b>NCERT Reference:</b> ${q.reference}`;$("concept").textContent="🧠 "+q.explain;$("repairQ").textContent=q.repairQ;let r=$("repairTargets");r.innerHTML="";q.repairOptions.forEach((o,i)=>{let x=document.createElement("button");x.className="target";x.textContent=String.fromCharCode(65+i)+"  "+o;x.onclick=()=>repair(i,x);r.appendChild(x)});$("pdfChoice").style.display="block";show("repair")}
function repair(i,b){let q=S.qs[S.i];[...$("repairTargets").children].forEach(x=>x.disabled=true);if(i===q.repairAnswer){S.score+=15;S.coins+=5;$("concept").textContent="🧠 CONCEPT REPAIRED! +15 XP"}else $("concept").textContent="💡 Review the NCERT reference and try again later.";hud();setTimeout(next,900)}
function next(){if(S.lives<=0){finish(false);return}S.i++;if(S.i>=S.qs.length){finish(true);return}show("game");loadQ()}
function finish(win){clearInterval(S.tid);let p=JSON.parse(localStorage.getItem(KEY)||"{}");p.score=Math.max(p.score||0,S.score);p.coins=Math.max(p.coins||0,S.coins);p.correct=Math.max(p.correct||0,S.correct);p.name=S.name;p.lastChapter=C[1];localStorage.setItem(KEY,JSON.stringify(p));$("finalScore").textContent=S.score;$("finalCoins").textContent=S.coins;$("finalCorrect").textContent=S.correct;$("resultTitle").textContent=win?"🏆 CHAPTER MASTER!":"💥 QUEST PAUSED";$("resultText").textContent=`${S.correct} correct out of ${S.qs.length}. Your local progress is saved.`;show("result");loadProfile()}
$("mathBtn").onclick=()=>chooseSubject("math");$("scienceBtn").onclick=()=>chooseSubject("science");$("homeBtn").onclick=()=>show("home");$("backChapters").onclick=()=>show("chapters");$("playChapter").onclick=startGame;$("gameHome").onclick=()=>{clearInterval(S?.tid);show("home")};$("again").onclick=startGame;$("resultChapters").onclick=()=>{renderChapters();show("chapters")};$("skipReference").onclick=next;$("openReference").onclick=()=>window.open(pdfFor(C),"_blank","noopener");loadProfile();loadBanks();