(function(){
'use strict';
const $=id=>document.getElementById(id), KEY='aarikaAdventureLeaderboardV1';
const MATH=[['1','Real Numbers','💎','Number Mine'],['2','Polynomials','🧩','Polynomial Puzzle'],['3','Pair of Linear Equations in Two Variables','🚂','Equation Express'],['4','Quadratic Equations','🏎️','Formula Race'],['5','Arithmetic Progressions','🛤️','Sequence Runner'],['6','Triangles','🏰','Triangle Builder'],['7','Coordinate Geometry','🗺️','Coordinate Explorer'],['8','Introduction to Trigonometry','🎯','Target Quest'],['9','Some Applications of Trigonometry','🚁','Height Hunter'],['10','Circles','🎡','Circle Defender'],['11','Areas Related to Circles','🪙','Circle Treasure'],['12','Surface Areas and Volumes','🧱','Solid Builder'],['13','Statistics','🕵️','Data Detective'],['14','Probability','🎲','Probability Quest']];
const SCIENCE=[['1','Chemical Reactions and Equations','🧪','Reaction Lab'],['2','Acids, Bases and Salts','⚗️','pH Quest'],['3','Metals and Non-metals','⛏️','Metal Forge'],['4','Carbon and its Compounds','🧬','Carbon City'],['5','Life Processes','🫀','Life Mission'],['6','Control and Coordination','🧠','Neuro Mission'],['7','How do Organisms Reproduce?','🧬','Life Cycle Quest'],['8','Heredity','🧬','Gene Lab'],['9','Light – Reflection and Refraction','🔦','Photon Quest'],['10','The Human Eye and the Colourful World','👁️','Vision World'],['11','Electricity','⚡','Power Grid'],['12','Magnetic Effects of Electric Current','🧲','Magnet Mission'],['13','Our Environment','🌍','Eco Defender']];
let subject='', chapter=null, state=null;
function page(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');window.scrollTo(0,0)}
function profile(){const p=JSON.parse(localStorage.getItem(KEY)||'[]');const best=p.length?p.reduce((a,b)=>a.score>b.score?a:b):null;$('score').textContent=best?best.score:0;$('coins').textContent=best?best.coins:0}
function choose(s){subject=s;const name=$('playerName').value.trim()||'Explorer';localStorage.setItem('aarikaPlayerName',name);renderChapters();page('chapters')}
function renderChapters(){const arr=subject==='science'?SCIENCE:MATH;$('subjectEyebrow').textContent='CLASS X • '+(subject==='science'?'SCIENCE':'MATHEMATICS');$('chapterGrid').innerHTML=arr.map((c,i)=>`<article class="chapter"><div class="icon">${c[2]}</div><h3>Chapter ${c[0]}: ${c[1]}</h3><div class="game">🎮 ${c[3]}</div><div class="actions"><button class="btn primary" data-ch="${i}">VIEW GAME</button></div></article>`).join('');document.querySelectorAll('[data-ch]').forEach(b=>b.onclick=()=>launch(+b.dataset.ch))}
function launch(i){chapter=(subject==='science'?SCIENCE:MATH)[i];$('launchIcon').textContent=chapter[2];$('launchNo').textContent=`CLASS X • ${subject.toUpperCase()} • CHAPTER ${chapter[0]}`;$('launchTitle').textContent=chapter[1];$('launchGame').textContent='🎮 '+chapter[3];$('launchText').textContent='100+ chapter-specific questions • unique questions • 60-second timer • lives • surprise bonuses • concept repair';page('launch')}
function getBank(){return (window.AARIKA_QUESTION_BANKS||{})[subject+'-'+chapter[0]]||[]}
function cleanBank(bank){const seen=new Set();return bank.filter(q=>{const k=String(q.q||'').trim().replace(/\s+/g,' ').toLowerCase();if(!k||seen.has(k)||!Array.isArray(q.options)||q.options.length<4)return false;seen.add(k);return true})}
function start(){const bank=cleanBank(getBank());if(!bank.length){alert('This chapter has no loaded questions.');return}const pool=bank.slice().sort(()=>Math.random()-.5);state={name:localStorage.getItem('aarikaPlayerName')||'Explorer',qs:pool.slice(0,20),i:0,score:0,coins:0,lives:3,streak:0,correct:0,totalTime:0,startedAt:Date.now(),timer:60,timerId:null,used:new Set(),repairDone:false};$('gameChapter').textContent=`CHAPTER ${chapter[0]} • ${chapter[1]}`;$('gameTitle').textContent=chapter[3];$('playerLabel').textContent=state.name;page('game');question()}
function question(){if(!state||state.i>=state.qs.length){finish(true);return}const q=state.qs[state.i],key=norm(q.q);if(state.used.has(key)){state.i++;return question()}state.used.add(key);$('gameTag').textContent=q.subtopic||q.topic||'Chapter Mission';$('question').textContent=q.q;$('qNo').textContent=state.i+1;$('gameFeedback').textContent='🎯 Choose your target!';$('enemy').textContent=['👹','🐲','👾','🧟','🦹'][state.i%5];const box=$('targets');box.innerHTML='';q.options.forEach((o,i)=>{const b=document.createElement('button');b.className='target';b.textContent=String.fromCharCode(65+i)+'  '+o;b.onclick=()=>answer(i,b);box.appendChild(b)});hud();clock()}
function norm(s){return String(s||'').trim().replace(/\s+/g,' ').toLowerCase()}
function clock(){clearInterval(state.timerId);state.timer=60;$('timer').textContent=60;state.timerId=setInterval(()=>{state.timer--;$('timer').textContent=state.timer;if(state.timer<=0){clearInterval(state.timerId);state.totalTime+=60;wrong(true)}},1000)}
function answer(i,b){clearInterval(state.timerId);state.totalTime+=60-state.timer;const q=state.qs[state.i];if(i===q.answer){b.classList.add('correct');state.correct++;state.streak++;state.score+=100+(state.streak%3===0?50:0);state.coins+=10;if(state.streak%3===0){state.coins+=25;$('gameFeedback').textContent='🎁 SURPRISE BONUS! +50 XP +25 COINS';}else $('gameFeedback').textContent='💥 HIT! +100 XP';hud();setTimeout(next,750)}else wrong(false,b)}
function wrong(timeout,b){clearInterval(state.timerId);state.lives--;state.streak=0;const q=state.qs[state.i];if(b)b.classList.add('wrong');document.querySelectorAll('#targets .target').forEach(x=>x.disabled=true);if($('targets').children[q.answer])$('targets').children[q.answer].classList.add('correct');$('mistake').textContent=timeout?'⏰ Time ran out!':'💥 Target missed!';$('reference').textContent='📚 Topic reference: '+(q.reference||('Chapter '+chapter[0]+' • '+(q.topic||'')));$('concept').textContent='🧠 '+(q.explain||'Review this chapter concept before continuing.');$('repairQ').textContent=q.repairQ||'Quick Fix: choose the statement that best explains this concept.';const rb=$('repairTargets');rb.innerHTML='';(q.repairOptions||q.options).forEach((o,i)=>{const x=document.createElement('button');x.className='target';x.textContent=String.fromCharCode(65+i)+'  '+o;x.onclick=()=>repair(i,x,q);rb.appendChild(x)});$('continueAfterRepair').disabled=true;state.repairDone=false;page('repair')}
function repair(i,b,q){document.querySelectorAll('#repairTargets .target').forEach(x=>x.disabled=true);if(i===(q.repairAnswer??q.answer)){b.classList.add('correct');state.score+=15;state.coins+=5;$('concept').textContent='🧠 CONCEPT REPAIRED! +15 XP';}else{b.classList.add('wrong');$('concept').textContent='💡 Good try. Read the topic reference above and remember the key idea.'}state.repairDone=true;$('continueAfterRepair').disabled=false;hud()}
function next(){if(state.lives<=0){finish(false);return}state.i++;if(state.i>=state.qs.length){finish(true);return}page('game');question()}
function finish(completed){clearInterval(state?.timerId);const avg=state.correct?Math.round(state.totalTime/state.correct):0;saveScore({...state,chapter:chapter[1],subject,avg});$('finalScore').textContent=state.score;$('finalCoins').textContent=state.coins;$('finalCorrect').textContent=state.correct;$('finalTime').textContent=avg;$('resultIcon').textContent=completed?'🏆':'💥';$('resultTitle').textContent=completed?'CHAPTER MASTER!':'QUEST OVER';$('resultText').textContent=`${state.correct}/${state.qs.length} correct • ${state.lives} lives left • score saved locally.`;page('result');profile()}
function saveScore(x){let a=JSON.parse(localStorage.getItem(KEY)||'[]');a.push({name:x.name,subject:x.subject,chapter:x.chapter,score:x.score,coins:x.coins,correct:x.correct,total:x.qs.length,date:new Date().toISOString()});a.sort((u,v)=>v.score-u.score);localStorage.setItem(KEY,JSON.stringify(a.slice(0,50)))}
function leaderboard(){const a=JSON.parse(localStorage.getItem(KEY)||'[]');$('leaderRows').innerHTML=a.length?a.slice(0,20).map((x,i)=>`<div class="leader-row"><b>#${i+1}</b><span>${esc(x.name)}</span><small>${esc(x.subject)} • ${esc(x.chapter)}</small><strong>⭐ ${x.score}</strong></div>`).join(''):'<div class="empty">No scores yet. Play a chapter!</div>';page('leaderboard')}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function clearBoard(){if(confirm('Clear all local leaderboard scores?')){localStorage.removeItem(KEY);profile();leaderboard()}}
function hud(){$('gScore').textContent=state.score;$('gCoins').textContent=state.coins;$('gLives').textContent=state.lives;$('gStreak').textContent=state.streak}
$('mathBtn').onclick=()=>choose('math');$('scienceBtn').onclick=()=>choose('science');$('homeBtn').onclick=()=>page('home');$('brandHome').onclick=()=>page('home');$('leaderBtn').onclick=leaderboard;$('leaderHome').onclick=leaderboard;$('leaderBack').onclick=()=>page('home');$('clearBoard').onclick=clearBoard;$('playChapter').onclick=start;$('backChapters').onclick=()=>page('chapters');$('gameHome').onclick=()=>{clearInterval(state?.timerId);page('home')};$('continueAfterRepair').onclick=next;$('again').onclick=start;$('resultChapters').onclick=()=>{renderChapters();page('chapters')};$('resultLeader').onclick=leaderboard;profile();
})();
