const BANK=QUESTION_BANK;const KEY="trigoQuestLeaderboardV2";
let S={name:"Explorer",score:0,coins:0,lives:3,streak:0,bestStreak:0,correct:0,index:0,timer:60,timerId:null,qs:[],hints:3,checkpoint:0,bossHP:5,bossIndex:0};
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(id).classList.add("active")}
function level(score){return score>=2500?"Trigo Legend":score>=1800?"Trigo Champion":score>=1200?"Trigo Master":score>=700?"CBSE Warrior":score>=300?"Ratio Ranger":"Triangle Rookie"}
function hud(){ $("score").textContent=S.score;$("coins").textContent=S.coins;$("lives").textContent=S.lives;$("streak").textContent=S.streak;$("timer").textContent=S.timer}
function save(){let b=read();let x=b.find(p=>p.name.toLowerCase()===S.name.toLowerCase());let r={name:S.name,score:S.score,coins:S.coins,correct:S.correct,bestStreak:S.bestStreak,level:level(S.score),last:new Date().toISOString()};if(x){Object.assign(x,{score:Math.max(x.score,r.score),coins:Math.max(x.coins,r.coins),correct:Math.max(x.correct,r.correct),bestStreak:Math.max(x.bestStreak,r.bestStreak),level:level(Math.max(x.score,r.score)),last:r.last})}else b.push(r);b.sort((a,c)=>c.score-a.score||c.correct-a.correct);localStorage.setItem(KEY,JSON.stringify(b.slice(0,100)))}
function read(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}
function renderLeaders(){let b=read();$("leaders").innerHTML=b.length?b.map((p,i)=>`<tr${p.name.toLowerCase()===S.name.toLowerCase()?' style="background:#263653"':''}><td>${i<3?["🥇","🥈","🥉"][i]:i+1}</td><td>${esc(p.name)}</td><td>⭐ ${p.score}</td><td>${p.correct}</td><td>🔥 ${p.bestStreak}</td><td>${p.level}</td></tr>`).join(""):'<tr><td colspan="6">No players yet.</td></tr>';let r=b.findIndex(p=>p.name.toLowerCase()===S.name.toLowerCase());$("myRank").textContent=r>=0?`🏅 Your local rank is #${r+1}`:"Play to enter the leaderboard."}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function start(){S={name:($("playerName").value.trim()||"Explorer"),score:0,coins:0,lives:3,streak:0,bestStreak:0,correct:0,index:0,timer:60,timerId:null,qs:[...BANK].sort(()=>Math.random()-.5).slice(0,20),hints:3,checkpoint:0,bossHP:5,bossIndex:0};$("nameLabel").textContent=S.name;show("game");load()}
function clock(){clearInterval(S.timerId);S.timer=60;hud();S.timerId=setInterval(()=>{S.timer--;hud();if(S.timer<=0){clearInterval(S.timerId);fail(true)}},1000)}
function load(){let q=S.qs[S.index];$("zoneName").textContent=["TRIGO VILLAGE","TRIANGLE FOREST","RATIO RANGE","ANGLE CITY","IDENTITY CASTLE"][Math.min(4,Math.floor(S.index/4))];$("topic").textContent=q.subtopic;$("tag").textContent=q.subtopic;$("question").textContent=q.q;$("qNo").textContent=`${S.index+1}/20`;$("bar").style.width=((S.index+1)/20*100)+"%";$("correct").textContent=S.correct;$("checkpoint").textContent=S.checkpoint;$("levelLabel").textContent=level(S.score);$("actionText").textContent="🎯 Choose the correct target!";let t=$("targets");t.innerHTML="";q.options.forEach((o,i)=>{let b=document.createElement("button");b.className="target";b.textContent=String.fromCharCode(65+i)+"  "+o;b.onclick=()=>answer(i,b);t.appendChild(b)});clock();hud()}
function lock(box){[...box.querySelectorAll(".target")].forEach(b=>b.disabled=true)}
function answer(i,b){if(b.disabled)return;clearInterval(S.timerId);let q=S.qs[S.index];if(i===q.answer){b.classList.add("correct");S.correct++;S.streak++;S.bestStreak=Math.max(S.bestStreak,S.streak);S.score+=100+(S.timer>=50?50:0)+(S.streak>=3?25:0);S.coins+=10;$("enemy").textContent="💥";$("actionText").textContent="💥 DIRECT HIT! +XP +COINS";lock($("targets"));hud();setTimeout(next,800)}else fail(false,b)}
function fail(timeout,b){let q=S.qs[S.index];S.lives--;S.streak=0;if(b)b.classList.add("wrong");let opts=[...$("targets").children];if(opts[q.answer])opts[q.answer].classList.add("correct");lock($("targets"));hud();$("mistake").textContent=timeout?`⏰ Time ran out! Correct answer: ${q.options[q.answer]}`:`💥 The Goblin blocked that shot. Correct answer: ${q.options[q.answer]}`;$("reference").textContent="📖 "+q.reference;$("concept").textContent="🎮 "+q.explain;$("repairQ").textContent=q.repairQ;let box=$("repairTargets");box.innerHTML="";q.repairOptions.forEach((o,i)=>{let x=document.createElement("button");x.className="target";x.textContent=String.fromCharCode(65+i)+"  "+o;x.onclick=()=>repair(i,x);box.appendChild(x)});show("repair")}
function repair(i,b){let q=S.qs[S.index];lock($("repairTargets"));if(i===q.repairAnswer){S.score+=15;S.coins+=5;$("concept").textContent="🧠 CONCEPT REPAIRED! +15 Learning XP";}else{$("concept").textContent="💡 Revisit "+q.reference+" before the next challenge."}hud();setTimeout(next,1000)}
function next(){if(S.lives<=0){save();finish(false);return}S.index++;if(S.index>=20){boss();return}if(S.index%4===0){S.checkpoint++;S.score+=100;S.coins+=25}show("game");load()}
const BOSS=[{q:"Which identity is always true?",o:["sin²A + cos²A = 1","sinA + cosA = 1","tan²A = 1","secA = tanA"],a:0},{q:"If tan A = 3/4, sin A is:",o:["3/5","4/5","5/4","3/4"],a:0},{q:"If sec A = 13/12, tan A is:",o:["5/12","12/5","13/5","5/13"],a:0},{q:"sin 30° + cos 60° =",o:["0","1/2","1","2"],a:2},{q:"(sec A − tan A)(sec A + tan A) =",o:["0","1","sec²A","tan²A"],a:1}];
function boss(){clearInterval(S.timerId);S.bossHP=5;S.bossIndex=0;show("boss");bossLoad()}
function bossLoad(){let q=BOSS[S.bossIndex];$("bossHealth").textContent="❤️".repeat(S.bossHP);$("bossQ").textContent=q.q;let box=$("bossTargets");box.innerHTML="";q.o.forEach((o,i)=>{let b=document.createElement("button");b.className="target";b.textContent=String.fromCharCode(65+i)+"  "+o;b.onclick=()=>bossAnswer(i,b);box.appendChild(b)})}
function bossAnswer(i,b){let q=BOSS[S.bossIndex];lock($("bossTargets"));if(i===q.a){S.bossHP--;S.score+=200;S.coins+=20;b.classList.add("correct");$("bossFeedback").textContent="💥 BOSS HIT!";}else{S.lives--;b.classList.add("wrong");$("bossFeedback").textContent="👹 BOSS ATTACK!";}hud();setTimeout(()=>{if(S.lives<=0){save();finish(false);return}if(S.bossHP<=0){save();finish(true);return}S.bossIndex=(S.bossIndex+1)%BOSS.length;bossLoad()},800)}
function finish(win){save();let b=read(),r=b.findIndex(p=>p.name.toLowerCase()===S.name.toLowerCase());$("finalScore").textContent=S.score;$("finalCoins").textContent=S.coins;$("finalRank").textContent=r+1;$("resultCharacter").textContent=win?"👑":"💥";$("resultTitle").textContent=win?"TRIGONOMETRY CHAMPION!":"QUEST ENDED";$("resultText").textContent=win?"You defeated the Trigo Boss and mastered the adventure!":"Your run is saved on the local leaderboard. Try again!";show("result")}
$("playBtn").onclick=start;$("mapBtn").onclick=()=>show("map");$("mapBack").onclick=()=>show("home");$("leaderBtn").onclick=()=>{renderLeaders();show("leaderboard")};$("leaderBack").onclick=()=>show("home");$("resultLeader").onclick=()=>{renderLeaders();show("leaderboard")};$("again").onclick=start;$("clearData").onclick=()=>{if(confirm("Clear all local leaderboard records?")){localStorage.removeItem(KEY);renderLeaders()}};$("hintBtn").onclick=()=>{if(S.hints>0&&S.coins>=10){S.hints--;S.coins-=10;let q=S.qs[S.index];let wrong=[0,1,2,3].filter(i=>i!==q.answer).sort(()=>Math.random()-.5).slice(0,2);wrong.forEach(i=>$("targets").children[i].disabled=true);$("actionText").textContent="💡 Two wrong targets eliminated!";hud()}else $("actionText").textContent="Need 10 coins for a hint."};hud();
